name: Print Name

on:
  push:
    branches:
      - main

jobs:
  print_name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Print Name
        run: |
          echo "Marian Pinzel"
